packages:
  - '.'

onlyBuiltDependencies:
  - '@swc/core'
  - bcrypt
  - cypress
  - sharp
  - sqlite3

overrides:
  sqlite3>node-gyp: 8.4.1
  '@types/express-session': 1.18.2
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
