import type DiscoverSlider from '@server/entity/DiscoverSlider';

export enum DiscoverSliderType {
  RECENTLY_ADDED = 1,
  RECENT_REQUESTS,
  PLEX_WATCHLIST,
  TRENDING,
  POPULAR_MOVIES,
  MOVIE_GENRES,
  UPCOMING_MOVIES,
  STUDIOS,
  POPULAR_TV,
  TV_GENRES,
  UPCOMING_TV,
  NETWORKS,
  TMDB_MOVIE_KEYWORD,
  TMDB_MOVIE_GENRE,
  TMDB_TV_KEYWORD,
  TMDB_TV_GENRE,
  TMDB_SEARCH,
  TMDB_STUDIO,
  TMDB_NETWORK,
  TMDB_MOVIE_STREAMING_SERVICES,
  TMDB_TV_STREAMING_SERVICES,
  TRAKT_RECOMMENDATIONS,
  TRAKT_WATCHLIST,
  TRAKT_LIST,
  TRAKT_HISTORY,
  ANILIST_TRENDING,
  ANILIST_SEASON,
  ANILIST_WATCHING,
  ANILIST_PLANNING,
  ANILIST_COMPLETED,
  ANILIST_LIST,
}

export const defaultSliders: Partial<DiscoverSlider>[] = [
  {
    type: DiscoverSliderType.RECENTLY_ADDED,
    enabled: true,
    isBuiltIn: true,
    order: 0,
  },
  {
    type: DiscoverSliderType.RECENT_REQUESTS,
    enabled: true,
    isBuiltIn: true,
    order: 1,
  },
  {
    type: DiscoverSliderType.PLEX_WATCHLIST,
    enabled: true,
    isBuiltIn: true,
    order: 2,
  },
  {
    type: DiscoverSliderType.TRENDING,
    enabled: true,
    isBuiltIn: true,
    order: 3,
  },
  {
    type: DiscoverSliderType.POPULAR_MOVIES,
    enabled: true,
    isBuiltIn: true,
    order: 4,
  },
  {
    type: DiscoverSliderType.MOVIE_GENRES,
    enabled: true,
    isBuiltIn: true,
    order: 5,
  },
  {
    type: DiscoverSliderType.UPCOMING_MOVIES,
    enabled: true,
    isBuiltIn: true,
    order: 6,
  },
  {
    type: DiscoverSliderType.STUDIOS,
    enabled: true,
    isBuiltIn: true,
    order: 7,
  },
  {
    type: DiscoverSliderType.POPULAR_TV,
    enabled: true,
    isBuiltIn: true,
    order: 8,
  },
  {
    type: DiscoverSliderType.TV_GENRES,
    enabled: true,
    isBuiltIn: true,
    order: 9,
  },
  {
    type: DiscoverSliderType.UPCOMING_TV,
    enabled: true,
    isBuiltIn: true,
    order: 10,
  },
  {
    type: DiscoverSliderType.NETWORKS,
    enabled: true,
    isBuiltIn: true,
    order: 11,
  },
  {
    type: DiscoverSliderType.TRAKT_RECOMMENDATIONS,
    enabled: true,
    isBuiltIn: true,
    order: 12,
  },
  {
    type: DiscoverSliderType.TRAKT_WATCHLIST,
    enabled: true,
    isBuiltIn: true,
    order: 13,
  },
  {
    type: DiscoverSliderType.TRAKT_HISTORY,
    enabled: true,
    isBuiltIn: true,
    order: 14,
  },
  {
    type: DiscoverSliderType.ANILIST_TRENDING,
    enabled: true,
    isBuiltIn: true,
    order: 15,
  },
  {
    type: DiscoverSliderType.ANILIST_SEASON,
    enabled: true,
    isBuiltIn: true,
    order: 16,
  },
  {
    type: DiscoverSliderType.ANILIST_WATCHING,
    enabled: true,
    isBuiltIn: true,
    order: 17,
  },
  {
    type: DiscoverSliderType.ANILIST_PLANNING,
    enabled: true,
    isBuiltIn: true,
    order: 18,
  },
  {
    type: DiscoverSliderType.ANILIST_COMPLETED,
    enabled: true,
    isBuiltIn: true,
    order: 19,
  },
];
